on: [push]

jobs:
  selenium_docker:
    runs-on: ubuntu-latest
    name: Selenium Docker
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: hello
        uses: ./ # Uses an action in the root directory
        id: selenium-test
        with:
          who-to-greet: 'LOCUS who'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"